# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-inntekt-klassifiserer
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  kafka:
    pool: {{kafka.pool}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  webproxy: true
  env:
    - name: DP_INNTEKT_API_SCOPE
      value: {{dp_inntekt.scope}}
  envFrom:
    - secret: dp-inntekt-klassifiserer-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io