apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: dp-inntekt-klassifiserer-unleash-api-token
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamdagpenger
  secretName: dp-inntekt-klassifiserer-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{unleash.environment}}