apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-klassifiserer
spec:
  vault:
    paths:
      - kvPath: "serviceuser/data/prod/srvdp-inntekt-klas"
        mountPath: "/secrets/serviceuser/srvdp-inntekt-klas"
