apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-klassifiserer
spec:
  vault:
    paths:
      - kvPath: "serviceuser/data/prod/srvdp-inntekt-klas"
        mountPath: "/secrets/serviceuser/srvdp-inntekt-klas"
      - kvPath: "kv/prod/fss/dp-inntekt-klassifiserer/default"
        mountPath: "/var/run/secrets/nais.io/vault/"
  replicas:
    min: 4
    max: 6
