apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-klassifiserer
spec:
  vault:
    paths:
      - kvPath: "serviceuser/data/dev/srvdp-inntekt-klas"
        mountPath: "/var/run/secrets/nais.io/service_user"
      - kvPath: "kv/preprod/fss/dp-inntekt-klassifiserer/default"
        mountPath: "/var/run/secrets/nais.io/vault/"
