apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-klassifiserer
spec:
  env:
    - name:  KAFKA_BOOTSTRAP_SERVERS
      value: "b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443"
